# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:stable
    steps:
      - checkout
      - run:
          name: "install"
          command: "yarn"
      - run:
          name: "test"
          command: "yarn test"
      - run:
          name: "lint types"
          command: "yarn lint:types"

workflows:
  ci:
    jobs:
      - test
